server:
  port: 8088
  address: 0.0.0.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true

spring:
  application:
    name: spring-boot-playground

  boot:
    admin:
      client:
        url: http://localhost:8081/

  datasource:
    url: jdbc:postgresql://localhost:5432/sandbox-rest-app #TODO variabilize ${ENV_VAR: def-val}
    username: sandbox-rest-app-user
    password: sandbox-rest-app-user-pwd
    driver-class-name: org.postgresql.Driver
#    hikari:
#      connection-test-query: SELECT 1
#      connection-timeout:
#      idle-timeout:
#      keepalive-time:
#      validation-timeout:
#      max-lifetime:

  jpa:
    show-sql: true    # Helpful during development to see the SQL
    generate-ddl: false # We want Liquibase, not Hibernate, to manage our schema
#    properties:
#      hibernate:
#        format_sql: true
        # Show values in queries instead of ?
#        type: trace
#    hibernate:
#      ddl-auto: none  # We want Liquibase, not Hibernate, to manage our schema
#    database-platform: org.hibernate.dialect.PostgreSQLDialect


  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

management:
  endpoint:
#    metrics:
#      enabled: false
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
#        include: "*"
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

#        include: health,info,shutdown
logging:
  level:
#    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
#    org:
#      springdoc: DEBUG
