server:
  port: ${SERVER_PORT:8088}
  address: ${SERVER_ADDRESS:0.0.0.0}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:spring-boot-playground}
  output:
    ansi:
      enabled: ALWAYS

  security:
    oauth2:
      authorizationserver:
        endpoint:
          authorization-uri: ${OAUTH2_AUTHORIZATION_URI:http://localhost:8082/realms/playground-realm/protocol/openid-connect/auth}
          token-uri: ${OAUTH2_TOKEN_URI:http://localhost:8082/realms/playground-realm/protocol/openid-connect/token}
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_JWT_ISSUER_URI:http://localhost:8082/realms/playground-realm}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI:http://localhost:8082/realms/playground-realm/protocol/openid-connect/certs}

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: false  # true for 1-based page numbers
        page-parameter: page
        size-parameter: size
        prefix: ""  # for prefix like "x.page" instead of "page"
      sort:
        sort-parameter: sort

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL:http://localhost:8081/}
        instance:
#          service-url: ${SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_URL:http://host.docker.internal:8088}
          service-url: ${SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_URL:http://${server.address}:${server.port}}
          metadata:
            tags:
              environment: ${ENVIRONMENT:local}
              version: @project.version@
              application-type: rest-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sandbox-rest-app}
    username: ${SPRING_DATASOURCE_USERNAME:sandbox-rest-app-user}
    password: ${SPRING_DATASOURCE_PASSWORD:sandbox-rest-app-user-pwd}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:true}    # Helpful during development to see the SQL
    generate-ddl: ${SPRING_JPA_GENERATE_DDL:false} # We want Liquibase, not Hibernate, to manage our schema

  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
    change-log: ${SPRING_LIQUIBASE_CHANGE_LOG:classpath:db/changelog/db.changelog-master.xml}
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}

springdoc:
  show-actuator: ${SHOW_ACTUATOR:true}
  swagger-ui:
    path: ${SWAGGER_UI_PATH:/swagger-ui.html}
    try-it-out-enabled: true
    oauth:
      client-id: ${SWAGGER_CLIENT_ID:playground-swagger-ui-client}
      scopes: ${SWAGGER_CLIENT_SCOPES:openid,profile}

playground:
  api:
    rest:
      data-generator:
        enabled: ${PLAYGROUND_API_REST_DATA_GENERATOR_ENABLED:false}
      sandbox:
        enabled: ${PLAYGROUND_API_REST_SANDBOX_ENABLED:false}

management:
  endpoint:
#    metrics:
#      enabled: true
##      enabled: false
    shutdown:
      enabled: ${MANAGEMENT_ENDPOINT_SHUTDOWN_ENABLED:false}
  endpoints:
    web:
      exposure:
#        exclude: shutdown
        include: "*"
#        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,prometheus}
#        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics,prometheus}
  prometheus:
    metrics:
      export:
        enabled: ${MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED:true}
#  security:
#    enabled: ${MANAGEMENT_SECURITY_ENABLED:false}

logging:
  level:
#    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: ${LOGGING_LEVEL_ORG_HIBERNATE_ORM_JDBC_BIND:TRACE}
#    org:
#      springdoc: DEBUG
